### ISSUE TITLE
Question about the role of value prediction loss

### ISSUE THREAD

**Issue by return-sleep** [nicklashansen/tdmpc2#15]
Thank you for your wonderful work. I am very curious, what would happen if when training a world model, the value estimation one is dropped and only dynamics loss and reward loss are used for training? Does this world model learn effective latent space, since it lacks the self-supervised signal for reconstruction compared to dreamer.

**Comment by nicklashansen** [comment]
This is a great question that I don't have a very conclusive answer to at the moment. In my experience, whether one can get away with using only either the dynamics loss or the reward/value prediction losses seem to depend on the particular task. This paper [Simplified Temporal Consistency Reinforcement Learning](https://arxiv.org/abs/2306.09466) finds that detaching reward/value prediction from the dynamics model can indeed improve sample-efficiency in some cases, but the gains are not very consistent. I would definitely be interested in exploring this more.

**Comment by nicklashansen** [comment]
Closing this issue but feel free to reopen if you have any follow-up questions!
