### ISSUE TITLE
About downloading data from huggingface

### ISSUE THREAD

**Issue by mynsng** [nicklashansen/tdmpc2#16]
Hello, congratulations on the ICLR acceptance.

I've read the paper thoroughly and I'm really grateful for sharing both the model and the data. However, I encountered an error while trying to download the data from Hugging Face, and I have a question about it.

I attempted to download the dataset using the following method:
```python
import datasets
ds = datasets.load_dataset('nicklashansen/tdmpc2')
```

However, I received the following error:
```python
DataFilesNotFoundError: No (supported) data files found in nicklashansen/tdmpc2
```

Could it be that I am using the wrong method to download the data? If there is an alternative method, please let me know. Thank you!

**Comment by nicklashansen** [comment]
Hi @mynsng, thank you!

I'll need to look into whether the dataset is configured correctly for API use, I suspect that I might have missed a step (first time uploading a dataset to huggingface). In the mean time, you should be able to download each shard/chunk of the dataset manually with
```
wget https://huggingface.co/datasets/nicklashansen/tdmpc2/resolve/main/mt80/chunk_0.pt?download=true
```
Apologies for the inconvenience!

**Comment by mynsng** [comment]
It works! Thank you for your efforts!
