### ISSUE TITLE
data loading typo

### ISSUE THREAD

**Issue by quantumiracle** [nicklashansen/tdmpc2#27]
Hi, this [line](https://github.com/nicklashansen/tdmpc2/blob/5f6fadec0fec78304b4b53e8171d348b58cac486/tdmpc2/trainer/offline_trainer.py#L68) should be:
```
assert self.buffer.num_eps == (self.buffer.capacity // _cfg.episode_length), \
	f'Buffer has {self.buffer.num_eps} episodes, expected {self.buffer.capacity // _cfg.episode_length} episodes.'
```

**Comment by nicklashansen** [comment]
Great catch! This seems to be a leftover from the previous buffer implementation (pre commit https://github.com/nicklashansen/tdmpc2/commit/54145a4d8c4c080836ff1f186fc5a87f70c8a8c7). I'll fix this soon and double-check that everything else in the offline trainer works as expected.

**Comment by nicklashansen** [comment]
Closing this issue since it was fixed a while ago. Thanks again for reporting it!
