### ISSUE TITLE
Question About "Lift Cube" Task in ManiSkill2

### ISSUE THREAD

**Issue by TongZhangTHU** [nicklashansen/tdmpc2#30]
Hi, 

Thank you for your wonderful work. I noticed that you use the "Lift Cube" task in ManiSkill2, but I couldn't find any documentation about it in ManiSkill2. Could you please explain the difference between "Lift Cube" and "Pick Cube"?

Thank you!

**Comment by nicklashansen** [comment]
Glad to hear that you find our work interesting! The two tasks are defined here: [](https://github.com/haosulab/ManiSkill/blob/v0.5.3/mani_skill2/envs/pick_and_place/pick_cube.py)

The main difference is that Pick Cube is goal-conditioned (grasp and move object to target location) whereas Lift Cube is conditioned on object height only.

**Comment by TongZhangTHU** [comment]
Thank you so much for your kind help!
