### ISSUE TITLE
cannot conduct "mt" experiments

### ISSUE THREAD

**Issue by kaiyama12345679** [nicklashansen/tdmpc2#35]
When I try
```
python train.py task=mt80 model_size=48 batch_size=1024
```
I got the following error
```
AssertionError: Expected data directory /root/data to contain mt80, please double-check your config
```

**Comment by nicklashansen** [comment]
Hi @kaiyama12345679, did you download the mt80 dataset from our website? It is available here: https://www.tdmpc2.com/dataset
After downloading, you will need to point to the dataset using the `data_dir` argument. I hope this helps!

**Comment by kaiyama12345679** [comment]
@nicklashansen, thank you so much for your reply. I have downloaded the `mt30` and `mt80` from your huggingface repository to `/root/data`, and set `data_dir=/root/data`.
However the above error still occured in my environments.

**Comment by kaiyama12345679** [comment]
I'm sorry, I misunderstood. When I set `data_dir=/root/data/mt30` or `data_dir=/root/data/mt80`, it works!
Thank you for your help!

**Comment by nicklashansen** [comment]
Great that you solved it!
