### ISSUE TITLE
[Questions] Support for Discrete Action Spaces in TDMPC2 Agent

### ISSUE THREAD

**Issue by hanshuo-shuo** [nicklashansen/tdmpc2#42]
Hi all, 

I'm currently working on modifying the TDMPC2 agent to handle discrete action spaces, but I've hit a bit of a roadblock and could use some guidance.

While I've been working on this modification, I've also been questioning whether adapting TDMPC2 for discrete actions is advisable. Since all the examples from the original paper are focused on continuous action spaces, I’m wondering if forcing a discrete action space might lead to suboptimal performance or other issues.

Thx

**Comment by hanshuo-shuo** [comment]
I noticed from tdmpc-1 https://github.com/nicklashansen/tdmpc/issues/1
It seems mpc only supports continuous action space.

**Comment by nicklashansen** [comment]
MPC is inherently a continuous space planning algorithm. It might be possible to extend it to discrete action spaces and/or mixed continuous/discrete spaces, but a more straightforward solution would be to replace the MPC planner with e.g. MCTS. Another option would be to disable planning and rely solely on the policy prior, but I don't know how well that would work. In continuous action spaces, I find that planning is very helpful for complex tasks while you can sometimes get away with not using planning if the task is pretty simple. Either way, the policy prior of TD-MPC is a maximum entropy policy which should be fairly easy to adapt to discrete action spaces.

**Comment by hanshuo-shuo** [comment]
> MPC is inherently a continuous space planning algorithm. It might be possible to extend it to discrete action spaces and/or mixed continuous/discrete spaces, but a more straightforward solution would be to replace the MPC planner with e.g. MCTS. Another option would be to disable planning and rely solely on the policy prior, but I don't know how well that would work. In continuous action spaces, I find that planning is very helpful for complex tasks while you can sometimes get away with not using planning if the task is pretty simple. Either way, the policy prior of TD-MPC is a maximum entropy policy which should be fairly easy to adapt to discrete action spaces.

Thanks!
