### ISSUE TITLE
Clarification regarding OnlineTrainer._step, env_step and action_repeat

### ISSUE THREAD

**Issue by aidanscannell** [nicklashansen/tdmpc2#45]
Hi, 

First of all, thanks for the great repo.

I want to compare my method to TD-MPC2 but I have a question regarding how you have reported results for TD-MPC2. The `OnlineTrainer` class increases `self._step` by 1 for each action executed in the environment. However, as TD-MPC2 uses `action_repeat=2` the environment step should be calculated as `self._step*action_repeat`. Please can you confirm if the `.csv` results files contain:

1. The raw `_step` from  `OnlineTrainer`, such that they need to be multiplied by `action_repeat` to get the environment step.
2. Or have they been post-processed and multiplied by action repeat already?

Cheers,
Aidan

**Comment by nicklashansen** [comment]
Hi Aidan, thanks for reaching out! You're right that we do not account for action repeat in the OnlineTrainer. Action repeat is applied as a post-processing step before plotting / dumping to csv so the results in [results/](https://github.com/nicklashansen/tdmpc2/tree/main/results) indeed do account for action repeat. You should be able to reproduce our figures exactly using the provided data. I hope this helps :-)

**Comment by nicklashansen** [comment]
Also FYI I recently released results for all methods in the paper, so if you would like to compare to our baselines as well that's also an option!

**Comment by aidanscannell** [comment]
Great, thank you.
