### ISSUE TITLE
Checkpoints for non-expert policies for MetaWorld

### ISSUE THREAD

**Issue by aliang8** [nicklashansen/tdmpc2#50]
Hi Nicklas, 

Thank you for release the checkpoints and datasets! This is super useful for the community. I noticed that the released checkpoints for MW are different seeds of the expert policy. I was wondering if you also plan to release the intermediate checkpoints (for random / medium-expert policies). Thank you!

**Comment by nicklashansen** [comment]
Hi @aliang8, I'm glad that you find it useful! We did not retain intermediate checkpoints and have no plans to release any at this time. However, it should be fairly straightforward to generate them yourself using our tdmpc2 online RL training script. One thing to keep in mind though would be that rate of convergence can differ quite substantially between tasks in Meta-World, so you would probably have to keep track of the success rate and save checkpoints when you are at your target performance level :-)

**Comment by aliang8** [comment]
Thanks for the reply!
