### ISSUE TITLE
GPU can be detected but torch.cuda.available() returns False in docker container

### ISSUE THREAD

**Issue by soulde** [nicklashansen/tdmpc2#51]
I use the dockerfile to build the image and run the docker container with `docker run -it --rm -e DISPLAY=host.docker.internal:0.0 --gpus all -v <my path>:/root/tdmpc2 --name tdmpc2_container  tdmpc2`.
When I call `nvidia-smi`, it returns
![image](https://github.com/user-attachments/assets/acda9088-dafd-4f2b-b84c-d4358972c878)
but `torch.cuda.available()` returns False.
I guess the torch version changed and pytorch.org  told me conda packages are no longer available. 
So how can I set up the environment, can I use the stable version?
I changed the mojuco to mujoco_py and it is supposed to have nothing to do with the GPU availability issue.

**Comment by nicklashansen** [comment]
Hi @soulde, it is possible that our recent update has broken the docker build process. Let me look into that. In the meantime, you have two options: (1) revert to a previous commit e.g. `d`, or (2) use the prebuilt image available at https://hub.docker.com/r/nicklashansen/tdmpc2 (`docker pull nicklashansen/tdmpc2`). Naturally, that would mean you no longer benefit from the wall-time speedups introduced in our recent commit, but it could be a good temporary solution.

**Comment by nicklashansen** [comment]
Hi again, I have updated the Dockerfile and environment.yaml files and tested that it supports the new `torch.compile` functionality that we introduced a few weeks ago. This is the relevant commit: https://github.com/nicklashansen/tdmpc2/commit/0a79c8bd38a0a49a011762ffc02c42dd15b0f5d4

Let me know whether this works on your end too!

**Comment by soulde** [comment]
Thank you for updating the code so quickly. It works great now for me.
