### ISSUE TITLE
Finetuning multitask model on a new task

### ISSUE THREAD

**Issue by JonaSchulz** [nicklashansen/tdmpc2#53]
I am trying to train TD-MPC2 on a new custom environment. It is unclear to me how to best make use of the pretrained multitask models you provide. In the paper you describe finetuning by initializing the task embedding for the novel task and then training the multitask model on the novel task. How can this be done in practice with the code provided here? Loading a multitask checkpoint into a model configured for a single task does not work as the state_dicts are not compatible.

Thanks a lot! I greatly appreciate making this model and the checkpoints publicly available!

**Comment by nicklashansen** [comment]
Great question! The only difference between the multi-task model and the default single-task model architecture is the additional learnable task embedding that all components are conditioned on. Our released codebase is not quite set up for finetuning experiments out of the box, but I believe you should be able to init the model by forcing `cfg.multitask` to be true here

https://github.com/nicklashansen/tdmpc2/blob/df8a465c8e137c652a142f6ad6cdf540d3a6a39a/tdmpc2/common/parser.py#L70-L71

We didn't do anything overly complicated when finetuning. We simply picked a good init (i.e., a similar task) for the task embedding and finetuned the whole model end-to-end with online RL and default hparams. This is likely not the best way to do it, but it worked well enough for our purposes.

I hope this helps!

**Comment by nicklashansen** [comment]
> Is there any way I can avoid having to first create the complete multitask environment (such as mt80) in order to initialize all the hyperparameters such as action_dim, obs_dim and number of task embeddings required to load the model checkpoint?

You could directly set these values instead of inferring them from the environment.

> how do I deal with my custom environment having different observation and action spaces

We zero-pad observations and actions to the largest dims used during training, iirc it's 39 and 6 dims, respectively, but you might want to double-check that.

**Comment by JonaSchulz** [comment]
Thank you for helping out! I managed to make finetuning work.

**Comment by nicklashansen** [comment]
Great that you made it work! I'll close this issue but feel free to reopen if you have any follow-up questions.
