### ISSUE TITLE
Qustion about Offline Data Preprocess

### ISSUE THREAD

**Issue by yueyang130** [nicklashansen/tdmpc2#8]
Hi, @nicklashansen 

Thanks for your wonderful work!

I read your code for loading the offline multitask dataset and have a question. Specifially, as shown above, you make one timestep shift for action and reward w.r.t. obs. Does it means $a_{t+1}$ and $r_{t+1}$ correspond to $s_t$ in your data organization? And thus the first action and reward in an episode is useless (no corresponding state)?

https://github.com/nicklashansen/tdmpc2/blob/f3139291e2dc8e47480184a4a1bce05e8980caa3/tdmpc2/common/buffer.py#L28

**Comment by nicklashansen** [comment]
Hi @yueyang130, I just wanted to let you know that commit https://github.com/nicklashansen/tdmpc2/commit/1f6c7771b92edd8d5502f910d5582ebf8ee88675 has now changed the default behavior to assign `nan` values to all filler indices (along with various other code improvements). Closing this issue, but feel free to reopen or open another issue if you have any other questions.

**Comment by yueyang130** [comment]
Hi, Nicklas, I got it!

Thanks for your reminder!
